---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 3-flux-git-repo-config
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/kalebpederson/aks-policy-governance-3-flux-git-repo-config
